/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountStats } from './accountStats';


export interface Account { 
    id: string;
    userName?: string;
    password?: string;
    email?: string;
    emailVerified: boolean;
    stats?: AccountStats;
    characters?: Array<string>;
    dateJoined: Date;
    credits: number;
}
