/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Room } from './room';


export interface Area { 
    id: number;
    title?: string;
    description?: string;
    dateCreated?: Date;
    dateUpdated?: Date;
    createdBy?: string;
    modifiedBy?: Array<string>;
    rooms?: Array<Room>;
}
