/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ContainerSize = 0 | 1 | 2 | 3 | 4 | 5;

export const ContainerSize = {
    NUMBER_0: 0 as ContainerSize,
    NUMBER_1: 1 as ContainerSize,
    NUMBER_2: 2 as ContainerSize,
    NUMBER_3: 3 as ContainerSize,
    NUMBER_4: 4 as ContainerSize,
    NUMBER_5: 5 as ContainerSize
};
