/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContainerSize } from './containerSize';
import { Item } from './item';
import { LockStrength } from './lockStrength';


export interface Container { 
    size: ContainerSize;
    items?: Array<Item>;
    canOpen: boolean;
    isOpen: boolean;
    canLock: boolean;
    isLocked: boolean;
    goldPieces: number;
    associatedKeyId?: string;
    lockDifficulty: LockStrength;
}
