/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type DamageTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

export const DamageTypes = {
    NUMBER_0: 0 as DamageTypes,
    NUMBER_1: 1 as DamageTypes,
    NUMBER_2: 2 as DamageTypes,
    NUMBER_3: 3 as DamageTypes,
    NUMBER_4: 4 as DamageTypes,
    NUMBER_5: 5 as DamageTypes,
    NUMBER_6: 6 as DamageTypes,
    NUMBER_7: 7 as DamageTypes,
    NUMBER_8: 8 as DamageTypes,
    NUMBER_9: 9 as DamageTypes,
    NUMBER_10: 10 as DamageTypes,
    NUMBER_11: 11 as DamageTypes
};
