/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type EffectLocation = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096 | 8192 | 16384 | 32768 | 65536 | 65536 | 65536;

export const EffectLocation = {
    NUMBER_0: 0 as EffectLocation,
    NUMBER_1: 1 as EffectLocation,
    NUMBER_2: 2 as EffectLocation,
    NUMBER_4: 4 as EffectLocation,
    NUMBER_8: 8 as EffectLocation,
    NUMBER_16: 16 as EffectLocation,
    NUMBER_32: 32 as EffectLocation,
    NUMBER_64: 64 as EffectLocation,
    NUMBER_128: 128 as EffectLocation,
    NUMBER_256: 256 as EffectLocation,
    NUMBER_512: 512 as EffectLocation,
    NUMBER_1024: 1024 as EffectLocation,
    NUMBER_2048: 2048 as EffectLocation,
    NUMBER_4096: 4096 as EffectLocation,
    NUMBER_8192: 8192 as EffectLocation,
    NUMBER_16384: 16384 as EffectLocation,
    NUMBER_32768: 32768 as EffectLocation,
    NUMBER_65536: 65536 as EffectLocation,
    NUMBER_65536_2: 65536 as EffectLocation,
    NUMBER_65536_3: 65536 as EffectLocation
};
