/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type EqSlot = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;

export const EqSlot = {
    NUMBER_0: 0 as EqSlot,
    NUMBER_1: 1 as EqSlot,
    NUMBER_2: 2 as EqSlot,
    NUMBER_3: 3 as EqSlot,
    NUMBER_4: 4 as EqSlot,
    NUMBER_5: 5 as EqSlot,
    NUMBER_6: 6 as EqSlot,
    NUMBER_7: 7 as EqSlot,
    NUMBER_8: 8 as EqSlot,
    NUMBER_9: 9 as EqSlot,
    NUMBER_10: 10 as EqSlot,
    NUMBER_11: 11 as EqSlot,
    NUMBER_12: 12 as EqSlot,
    NUMBER_13: 13 as EqSlot,
    NUMBER_14: 14 as EqSlot,
    NUMBER_15: 15 as EqSlot,
    NUMBER_16: 16 as EqSlot
};
