/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Item } from './item';


export interface Equipment { 
    light?: Item;
    finger?: Item;
    finger2?: Item;
    neck?: Item;
    neck2?: Item;
    eyes?: Item;
    face?: Item;
    head?: Item;
    ear?: Item;
    torso?: Item;
    legs?: Item;
    feet?: Item;
    hands?: Item;
    arms?: Item;
    aboutBody?: Item;
    onBack?: Item;
    waist?: Item;
    wrist?: Item;
    wrist2?: Item;
    wielded?: Item;
    shield?: Item;
    held?: Item;
    floating?: Item;
    quiver?: Item;
}
