/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';


export interface Exit { 
    coords?: Coordinates;
    areaId: number;
    roomId: number;
    name?: string;
    keyword?: string;
    door: boolean;
    closed: boolean;
    locked: boolean;
    pickProof: boolean;
    noPass: boolean;
    noScan: boolean;
    hidden: boolean;
    lockId?: string;
}
