/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Exit } from './exit';


export interface ExitDirections { 
    north?: Exit;
    northEast?: Exit;
    east?: Exit;
    southEast?: Exit;
    south?: Exit;
    southWest?: Exit;
    west?: Exit;
    northWest?: Exit;
    up?: Exit;
    down?: Exit;
}
