/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ItemFlags = 0 | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096 | 8192 | 16384 | 32768 | 65536;

export const ItemFlags = {
    NUMBER_0: 0 as ItemFlags,
    NUMBER_1: 1 as ItemFlags,
    NUMBER_2: 2 as ItemFlags,
    NUMBER_4: 4 as ItemFlags,
    NUMBER_8: 8 as ItemFlags,
    NUMBER_16: 16 as ItemFlags,
    NUMBER_32: 32 as ItemFlags,
    NUMBER_64: 64 as ItemFlags,
    NUMBER_128: 128 as ItemFlags,
    NUMBER_256: 256 as ItemFlags,
    NUMBER_512: 512 as ItemFlags,
    NUMBER_1024: 1024 as ItemFlags,
    NUMBER_2048: 2048 as ItemFlags,
    NUMBER_4096: 4096 as ItemFlags,
    NUMBER_8192: 8192 as ItemFlags,
    NUMBER_16384: 16384 as ItemFlags,
    NUMBER_32768: 32768 as ItemFlags,
    NUMBER_65536: 65536 as ItemFlags
};
