/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ItemTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

export const ItemTypes = {
    NUMBER_0: 0 as ItemTypes,
    NUMBER_1: 1 as ItemTypes,
    NUMBER_2: 2 as ItemTypes,
    NUMBER_3: 3 as ItemTypes,
    NUMBER_4: 4 as ItemTypes,
    NUMBER_5: 5 as ItemTypes,
    NUMBER_6: 6 as ItemTypes,
    NUMBER_7: 7 as ItemTypes,
    NUMBER_8: 8 as ItemTypes,
    NUMBER_9: 9 as ItemTypes,
    NUMBER_10: 10 as ItemTypes,
    NUMBER_11: 11 as ItemTypes
};
