/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArmourRating } from './armourRating';
import { ArmourTypes } from './armourTypes';
import { AttackTypes } from './attackTypes';
import { BaseItem } from './baseItem';
import { Book } from './book';
import { Container } from './container';
import { Damage } from './damage';
import { DamageTypes } from './damageTypes';
import { Description } from './description';
import { EqSlot } from './eqSlot';
import { ItemFlags } from './itemFlags';
import { ItemTypes } from './itemTypes';
import { Modifier } from './modifier';
import { WeaponTypes } from './weaponTypes';


export interface Item extends BaseItem { 
    equipped: boolean;
    damageType: DamageTypes;
    armourType: ArmourTypes;
    itemFlag: ItemFlags;
    itemType: ItemTypes;
    attackType: AttackTypes;
    slot: EqSlot;
    weaponType: WeaponTypes;
    weaponSpeed: number;
    damage?: Damage;
    keyId: string;
    container?: Container;
    book?: Book;
    modifier?: Modifier;
    armourRating?: ArmourRating;
    weight: number;
    forageRank: number;
    uses: number;
    infinite: boolean;
}
