/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type LockStrength = 0 | 1 | 2 | 3 | 4;

export const LockStrength = {
    NUMBER_0: 0 as LockStrength,
    NUMBER_1: 1 as LockStrength,
    NUMBER_2: 2 as LockStrength,
    NUMBER_3: 3 as LockStrength,
    NUMBER_4: 4 as LockStrength
};
