/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Affects } from './affects';
import { ArmourRating } from './armourRating';
import { Attributes } from './attributes';
import { Character } from './character';
import { Config } from './config';
import { Equipment } from './equipment';
import { Item } from './item';
import { Money } from './money';
import { Stats } from './stats';
import { Status } from './status';


export interface Player extends Character { 
    joinedDate: Date;
    lastLoginTime: Date;
    lastCommandTime: Date;
    playTime: number;
}
