/**
 * My Title
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export type WeaponTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14;

export const WeaponTypes = {
    NUMBER_0: 0 as WeaponTypes,
    NUMBER_1: 1 as WeaponTypes,
    NUMBER_2: 2 as WeaponTypes,
    NUMBER_3: 3 as WeaponTypes,
    NUMBER_4: 4 as WeaponTypes,
    NUMBER_5: 5 as WeaponTypes,
    NUMBER_6: 6 as WeaponTypes,
    NUMBER_7: 7 as WeaponTypes,
    NUMBER_8: 8 as WeaponTypes,
    NUMBER_9: 9 as WeaponTypes,
    NUMBER_10: 10 as WeaponTypes,
    NUMBER_11: 11 as WeaponTypes,
    NUMBER_12: 12 as WeaponTypes,
    NUMBER_13: 13 as WeaponTypes,
    NUMBER_14: 14 as WeaponTypes
};
