export * from './account.service';
import { AccountService } from './account.service';
export * from './alignment.service';
import { AlignmentService } from './alignment.service';
export * from './area.service';
import { AreaService } from './area.service';
export * from './attackTypes.service';
import { AttackTypesService } from './attackTypes.service';
export * from './class.service';
import { ClassService } from './class.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './item.service';
import { ItemService } from './item.service';
export * from './mob.service';
import { MobService } from './mob.service';
export * from './player.service';
import { PlayerService } from './player.service';
export * from './race.service';
import { RaceService } from './race.service';
export * from './room.service';
import { RoomService } from './room.service';
export * from './status.service';
import { StatusService } from './status.service';
export const APIS = [AccountService, AlignmentService, AreaService, AttackTypesService, ClassService, DashboardService, ItemService, MobService, PlayerService, RaceService, RoomService, StatusService];
