apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: clientwebapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clientwebapp 
    spec:
      containers:
        - name: clientwebapp 
          image: randomcontainerregistry.azurecr.io/clientwebapp
          ports:
          - containerPort: 4200